[package]
name = "raytracing"
version = "0.0.0"
edition = "2024"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
lexopt = "0.3.1"
open = "5.3.3"
rand = "0.9.1"
rayon = "1.11.0"
